### ISSUE TITLE
Problem with libbsd

### ISSUE THREAD

**Issue by basxto** [liberated-cortex/CCOSS_dependencies#5]
It appears that libbsd does not get build properly sometimes.

```
baes.a ../CCOSS_dependencies/prepared//libz.a ../CCOSS_dependencies/prepared//libbsd.a ../CCOSS_dependencies/prepared//libgorilla.a -lopenal -lpthread -ldl
c++: error: ../CCOSS_dependencies/prepared//libbsd.a: No such file or directory
make: *** [Makefile:62: cortex] Error 1
```

Reference: https://github.com/DataRealms/CCOSS/issues/3#issuecomment-520578736

**Comment by Smilex** [comment]
I tried upgrading libbsd. I suspect the actual issue is that I mistakenly added generated files on the first commit. This should fix that.
